function output = addhermitiansymmetry(input)
    % this function takes a parallel stream  as input 
    % hermitian symmetry added columnwise
    output = [ zeros(1,size(input,2)) ; ...
               input ;...
               zeros(1,size(input,2)) ; ...
               conj( input(end:-1:1,:) ) ];
end